### ISSUE TITLE
hfst-foma doesn't build in 3.5.1

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#199]
From distributed version when trying to enable foma wrapper:

```
cmatrix.l:99:1: varoitus: ”fwrite”:n paluuarvoa ei huomioida, esitelty attribuutilla     warn_unused_result [-Wunused-result]
mv -f .deps/lex.cmatrix.Tpo .deps/lex.cmatrix.Po
/bin/sh ../../libtool --tag=CC   --mode=link gcc  -O2 -march=native -ggdb -Wall -Wextra  -lz  -lncurses   -o hfst_foma foma.o stack.o iface.o lex.interface.o lex.cmatrix.o     ../../back-ends/foma/libfoma.la -lz -lm -lpthread -ldl -lxml2 
libtool: link: gcc -O2 -march=native -ggdb -Wall -Wextra -o hfst_foma foma.o stack.o iface.o lex.interface.o lex.cmatrix.o  -lncurses ../../back-ends/foma/.libs/libfoma.a -lz -lm -lpthread -ldl -lxml2
iface.o: In function `iface_save_stack':
/home/flammie/Sources/hfst-3.5.1/back-ends/foma/iface.c:1015: undefined reference to `foma_net_print'
collect2: ld returned 1 exit status
make[3]: *** [hfst_foma] Virhe 1
make[3]: Poistutaan hakemistosta "/home/flammie/Sources/hfst-3.5.1/back-ends/foma"
```

reproduce by:

```
$ history
  566  ./configure --enable-lexc --enable-tagger --enable-calculate --enable-xfst --enable-foma-wrapper
  567  make
```

Reported by: flammie
