### ISSUE TITLE
sfst backend doesn't compile on MacOSX 10.8 with XCode 5

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#192]
Prerequisites as tested:

* MacOSX 10.8.4
* XCode 5.0
* Automake 1.14

Steps to reproduce:

```
$ cd hfst3
$ svn up -r3538
$ ./autogen.sh
$ ./configure --enable-lexc --enable-proc --enable-xfst2fst
$ make
[...]
/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../.. \
-I../../libhfst/src  -Wno-deprecated   -g -O2 -MT compact.lo -MD -MP -MF .deps/compact.Tpo \
-c -o compact.lo compact.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I../../libhfst/src -Wno-deprecated -g \
-O2 -MT compact.lo -MD -MP -MF .deps/compact.Tpo -c compact.cc  -fno-common \
-DPIC -o .libs/compact.o
compact.cc:267:20: error: variable length array of non-POD element type 'SFST::Label'
    Label Num2Label[alphabet.size()];
                   ^
1 error generated.
```

By disabling the sfst backend the compilation goes through:

```
$ ./configure --enable-lexc --enable-proc --enable-xfst2fst --without-sfst
```

Reported by: snomos
